[project]
name = "simpad"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dearpygui>=2.3.1",
    "sdl3>=0.2.0rc0",
    "glfw>=2.7.0",
    "pyside6>=6.11.2",
    "imgui-bundle>=1.92.900",
    "numpy>=2.5.2",
    "piper-tts>=1.2.0",
    "tqdm>=4.66.0",
    "isimotor-rawudp-client @ https://github.com/marcgardent/isiMotor-RawUDP-Plugin/releases/download/v0.1.3/isimotor_rawudp_client-0.1.3-py3-none-any.whl",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

