"""
SimPulse SDK — Official Python SDK for SimPulse Plugins and Subplugins.
Contains only contracts, protocols, and domain models for third-party plugin development.
"""

# Contracts & Protocols
from simpulse_sdk.contracts import (
    SimPulsePlugin,
    PluginContext,
    IPluginConfigProvider,
    ITelemetrySubscriber,
    IDeltaSubscriber,
    ITelemetryStateSubscriber,
    ITabProvider,
    IHudWidgetProvider,
    IParamDescriptor,
    ConfigParam,
    RoleParam,
    SubpluginParam,
    ParamDescriptor,
    BoolParam,
    IntRangeParam,
    FloatRangeParam,
    ChoiceParam,
    ParamScalarValue,
)

# Models
from simpulse_sdk.models import (
    VehicleSensors,
    TelemetryChannel,
    ChannelRequirement,
    ChannelMetrics,
    TelemetryRawPacket,
    TelemetryPayload,
    TelemetryWakeReason,
    LapDeltaPacket,
    SectorInfo,
    DeltaReferenceMode,
    TelemetryStateStore,
    PacketSlot,
    PluginMetadata,
    PluginState,
    PluginErrorReport,
    HudSlot,
    HudLayoutSpec,
    clamp,
    apply_response_curve,
    format_lap_time,
)

__all__ = [
    # Contracts & Protocols
    "SimPulsePlugin",
    "PluginContext",
    "IPluginConfigProvider",
    "ITelemetrySubscriber",
    "IDeltaSubscriber",
    "ITelemetryStateSubscriber",
    "ITabProvider",
    "IHudWidgetProvider",
    "IParamDescriptor",
    "ConfigParam",
    "RoleParam",
    "SubpluginParam",
    "ParamDescriptor",
    "BoolParam",
    "IntRangeParam",
    "FloatRangeParam",
    "ChoiceParam",
    "ParamScalarValue",
    # Models
    "VehicleSensors",
    "TelemetryChannel",
    "ChannelRequirement",
    "ChannelMetrics",
    "TelemetryRawPacket",
    "TelemetryPayload",
    "TelemetryWakeReason",
    "LapDeltaPacket",
    "SectorInfo",
    "DeltaReferenceMode",
    "TelemetryStateStore",
    "PacketSlot",
    "PluginMetadata",
    "PluginState",
    "PluginErrorReport",
    "HudSlot",
    "HudLayoutSpec",
    "clamp",
    "apply_response_curve",
    "format_lap_time",
]
